# DataSource
spring:
  profiles:
    active: dev
  #    default: dev
  datasource:
    # mariadb 연결
    username: koorung
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/koolog
    # mysql 연결
#    username: koorung
#    password: 1234
#    url: jdbc:mysql://localhost:3306/koorungblog
#    driver-class-name: com.mysql.cj.jdbc.Driver


  # JPA Option
  jpa:
    #    open-in-view: false  -> osiv설정을 끄면 뷰영역까지 영속성 컨텍스트가 유지되지 않는다.
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

# Logging
logging:
  level:
    org.hibernate.type.descriptor.sql: trace